language: ruby

rvm:
  - 2.1.2

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database app_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - RAILS_ENV=test bundle exec rake db:migrate spec